name: Gemini Issue Triage
on:
  issues:
    types: [opened, edited, labeled, unlabeled]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/run-gemini-cli@v0.1.18
        with:
          command: 'issue-triage'
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
