name: Gemini PR Review
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/run-gemini-cli@v0.1.18
        with:
          command: 'pr-review'
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}
